spring.application.name=javaSpringgapp
# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/secondbrain
spring.datasource.username=postgres
spring.datasource.password=Ankit@123
spring.jpa.hibernate.ddl-auto=update

# OpenAI Configuration
spring.ai.openai.api-key=${OPENAI_API_KEY}

# PGVector Store Configuration
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=1536
